apiVersion: v1
kind: Service
metadata:
  name: gst-public
  namespace: mvincze-playground
spec:
  type: LoadBalancer
  selector:
    app: gst
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
